name: samasuka
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  lottie: ^2.4.0
  flutter_pdfview: ^1.2.7
  dio: ^5.2.1
  path_provider: ^2.0.15
  intl: ^0.18.1
  get: 4.6.5
  get_storage: 2.1.1
  file_picker: ^5.3.2
  pdf: 3.10.4
  open_file: 3.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

